name: Build pypylon

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - '**'
    tags:
      - '*.*.*'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TWINE_USERNAME: __token__
  # Uncomment the relevant lines to switch between deployment to test.pypi.org or pypi.org
  TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
  # TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
  # TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: jfrog/setup-jfrog-cli@v4
      env:
       JF_URL: ${{ secrets.SDK_URL }}
       JF_ACCESS_TOKEN: ${{ secrets.SDK_TOKEN }}
 
    - name: Checkout repository
      uses: actions/checkout@v4
 
    # login
    - run: |
        jf c add --url=$JF_URL --access-token=$JF_ACCESS_TOKEN --interactive=false

    # download 
    - name: Download files from Artifactory
      id: get_sdks
      run: |
        set +x
        set -e
        build_config=$(cat .github/workflows/build_config.json)
        for os in $(echo $build_config | jq -r 'keys[]'); do
          for pylon_sdk in $(echo $build_config | jq -r --arg os "$os" '.[$os].pylon_sdks[]'); do
            if [[ $os == "windows" || $os == "macos" ]]; then
              jf rt dl --flat --props "pylon_os=${os,,};pylon_version=$pylon_sdk" "pylon-sdks-generic/*" ./${os,,}_sdk/
            elif [[ $os == "linux-x86_64" ]]; then
              jf rt dl --flat --props "pylon_architecture=x86_64;pylon_os=linux;pylon_version=$pylon_sdk" "pylon-sdks-generic/*" ./linux_x86_64_sdk/
            elif [[ $os == "linux-aarch64" ]]; then
              jf rt dl --flat --props "pylon_architecture=aarch64;pylon_os=linux;pylon_version=$pylon_sdk" "pylon-sdks-generic/*" ./linux_aarch64_sdk/
            fi
          done
        done

    - name: Upload Pylon SDK for Linux aarch64
      uses: actions/upload-artifact@v4
      with:
        name: Linux_aarch64_Pylon
        path: linux_aarch64_sdk
    
    - name: Upload Pylon SDK for Linux x86_64
      uses: actions/upload-artifact@v4
      with:
        name: Linux_x86_64_Pylon
        path: linux_x86_64_sdk

    - name: Upload Pylon SDK for Windows
      uses: actions/upload-artifact@v4
      with:
        name: Windows_Pylon
        path: windows_sdk

    - name: Upload Pylon SDK for macOS
      uses: actions/upload-artifact@v4
      with:
        name: macOS_Pylon
        path: macos_sdk

    - name: Check for release build
      id: check_release_build
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Build release for $GITHUB_REF"
        echo "release_build=1" >> $GITHUB_OUTPUT

    outputs:
      is_release_build: ${{ steps.check_release_build.outputs.env.release_build == '1' }}

  build-linux:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        a: [cp39, cp3_10, cp3_11, cp3_12]
        p: [manylinux_2_31_x86_64, manylinux_2_31_aarch64]

    env:
      P: ${{ matrix.p }}
      A: ${{ matrix.a }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # download the pylon sdks          
      - name: download linux artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: Linux*Pylon
          merge-multiple: true          
          path: pylon-installer

      - name: Display Structure of downloaded files
        run: ls -R pylon-installer

      - name: Build with docker
        run: |
          pwd
          ls
          ls pylon-installer
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          ./scripts/build/build-arch.sh --platform-tag $P --abi-tag $A --pylon-dir ./pylon-installer $ARGS

      # TODO: can we use v4 here?
      - uses: actions/upload-artifact@v3
        with:
          name: build-results-${{ matrix.p }}-${{ matrix.a }}
          path: dist/*

      - name: Upload Release Asset
        if: needs.setup.outputs.is_release_build == 'true'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*

      - name: Publish package to (Test)PyPI
        if: needs.setup.outputs.is_release_build == 'true' && startsWith( matrix.p, 'manylinux' )
        run: |
          sudo pip3 install twine
          python3 -m twine upload --non-interactive --skip-existing dist/*


  build-windows:
    needs: setup
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9 - 3.12"

      - uses: actions/download-artifact@v4
        with:
          name: Windows_Pylon
          path: pylon-installer

      - name: Display Structure of downloaded files
        run: dir pylon-installer

      - name: Setup pylon
        run: |
          cd pylon-installer
          ren Basler-pylon-*.exe Basler-pylon.exe
          Start-Process Basler-pylon.exe -Wait -ArgumentList '/quiet /install=GigE_Support;USB_Support;Camera_Link_Support;CoaXPress_Support;GenTL_Consumer_Support;CamEmu_Support;SDKs;DataProcessing_SDK'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19
        env:
          PYLON_DEV_DIR: "C:\\Program Files\\Basler\\pylon 7\\Development"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Upload Release Asset
        if: needs.setup.outputs.is_release_build == 'true'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./wheelhouse/*.whl

      - name: Publish package to (Test)PyPI
        if: needs.setup.outputs.is_release_build == 'true'
        run: |
          python -m pip install twine
          python -m twine upload --non-interactive --skip-existing wheelhouse\\*
        shell: cmd


  build-macos:
    needs: setup
    runs-on: macos-11
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9 - 3.12"

      - uses: actions/download-artifact@v4
        with:
          name: macOS_Pylon
          path: pylon-installer

      - name: Setup pylon
        run: |
          # install universal
          cd pylon-installer
          hdiutil attach pylon-*.dmg
          sudo installer -pkg /Volumes/pylon\ *\ Camera\ Software\ Suite/pylon-*.pkg  -target /
          hdiutil detach /Volumes/pylon\ *\ Camera\ Software\ Suite

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19
        env:
          PYLON_FRAMEWORK_ARM64: /Library/Frameworks
          PYLON_FRAMEWORK_X86_64: /Library/Frameworks

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Upload Release Asset
        if: needs.setup.outputs.is_release_build == 'true'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./wheelhouse/*.whl

      - name: Publish package to (Test)PyPI
        if: needs.setup.outputs.is_release_build == 'true'
        run: |
          sudo pip3 install twine
          python3 -m twine upload --non-interactive --skip-existing wheelhouse/*

  cleanup:
    if: always()
    needs: [
            setup,
            build-linux,
            build-macos,
            build-windows
           ]
    runs-on: ubuntu-latest
    steps:
    - uses: geekyeggo/delete-artifact@v5
      continue-on-error: true
      with:
        name: |
          Linux_x86_64_Pylon
          Linux_aarch64_Pylon
          Windows_Pylon
          macOS_Pylon


